import { MaterialIcons } from "@expo/vector-icons";
import { CameraView, useCameraPermissions } from "expo-camera";
import { useRouter } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { PrimaryButton, ui } from "@/components/fitness-ui";

export default function BarcodeScanScreen() {
  const router = useRouter(); const [permission, requestPermission] = useCameraPermissions(); const [scanned, setScanned] = useState(false);
  const handleScan = ({ data }: { data: string }) => { if (scanned) return; setScanned(true); router.replace({ pathname: "/nutrition", params: { barcode: data } } as never); };
  return <View style={ui.page}>{!permission ? <View style={styles.center}><Text style={styles.wait}>Kamera izni kontrol ediliyor…</Text></View> : !permission.granted ? <View style={styles.center}><View style={styles.info}><MaterialIcons name="qr-code-scanner" size={28} color="#B8FF3D" /><Text style={styles.title}>Barkod tarama için kamera gerekli</Text><Text style={styles.copy}>Besin paketindeki kodu cihazında okumak için izin ver.</Text><View style={{ width: "100%", marginTop: 18 }}><PrimaryButton label="Kamera İznini Ver" onPress={requestPermission} icon="videocam" /></View></View></View> : <CameraView style={styles.camera} facing="back" barcodeScannerSettings={{ barcodeTypes: ["ean13", "ean8", "upc_a", "upc_e", "code128"] }} onBarcodeScanned={handleScan}><View style={styles.overlay}><TouchableOpacity onPress={() => router.back()} style={styles.close}><MaterialIcons name="close" size={23} color="#F5F7FA" /></TouchableOpacity><View style={styles.frame}><View style={styles.corner} /></View><View style={styles.caption}><Text style={styles.captionText}>Barkodu çerçevenin içine hizala</Text></View></View></CameraView>}</View>;
}
const styles = StyleSheet.create({ center: { flex: 1, padding: 24, justifyContent: "center", backgroundColor: "#0B0E12" }, wait: { color: "#9AA6B5", textAlign: "center" }, info: { padding: 20, backgroundColor: "#141A22", borderColor: "#263141", borderWidth: 1, borderRadius: 22, alignItems: "center" }, title: { color: "#F5F7FA", fontSize: 17, fontWeight: "900", marginTop: 14 }, copy: { color: "#9AA6B5", fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 7 }, camera: { flex: 1 }, overlay: { flex: 1, justifyContent: "space-between", padding: 22, backgroundColor: "#0B0E1244" }, close: { width: 43, height: 43, borderRadius: 15, backgroundColor: "#0B0E12CC", alignItems: "center", justifyContent: "center" }, frame: { alignSelf: "center", width: "82%", aspectRatio: 1.5, borderWidth: 2, borderColor: "#B8FF3D", borderRadius: 20 }, corner: { width: 42, height: 42, borderLeftWidth: 5, borderTopWidth: 5, borderColor: "#B8FF3D", borderTopLeftRadius: 19, position: "absolute", top: -2, left: -2 }, caption: { alignSelf: "center", paddingHorizontal: 14, paddingVertical: 9, borderRadius: 99, backgroundColor: "#0B0E12CC" }, captionText: { color: "#F5F7FA", fontSize: 12, fontWeight: "800" } });
