import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { Card, PrimaryButton, SectionTitle, ui } from "@/components/fitness-ui";
import { useFitness } from "@/lib/fitness-store";

export default function CoachDeskScreen() {
  const router = useRouter(); const { data, addCoachTask, toggleCoachTask } = useFitness();
  const [title, setTitle] = useState(""); const [description, setDescription] = useState("");
  const completed = data.coachTasks.filter((task) => task.completed).length;
  return <View style={ui.page}><ScrollView contentContainerStyle={ui.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#D7DEE8" /><Text style={styles.backText}>Performans</Text></TouchableOpacity><Text style={ui.eyebrow}>Koç Çalışma Alanı</Text><Text style={ui.h1}>Planı takip et.</Text><Text style={[ui.body, { marginTop: 8 }]}>Koçtan gelen kontrol noktalarını veya kendi haftalık hedeflerini net görevler olarak tut.</Text><SectionTitle title="Haftalık durum" /><Card accent><View style={styles.statusRow}><View style={styles.statusIcon}><MaterialIcons name="assignment-turned-in" size={21} color="#B8FF3D" /></View><View style={{ flex: 1 }}><Text style={styles.statusTitle}>{completed}/{data.coachTasks.length} görev tamamlandı</Text><Text style={styles.statusCopy}>Programını paylaşmak veya koç programı içe aktarmak için Topluluk sekmesini kullan.</Text></View></View></Card><SectionTitle title="Yeni kontrol noktası" /><Card><TextInput value={title} onChangeText={setTitle} placeholder="Örn. Squat videonu kontrol et" placeholderTextColor="#657386" style={styles.input} /><TextInput value={description} onChangeText={setDescription} placeholder="Kısa not veya koç yönlendirmesi" placeholderTextColor="#657386" style={[styles.input, styles.note]} multiline /><View style={{ marginTop: 13 }}><PrimaryButton label="Görev Ekle" onPress={() => { if (!title.trim()) return; addCoachTask({ title: title.trim(), description: description.trim() || undefined }); setTitle(""); setDescription(""); }} icon="add-task" /></View></Card><SectionTitle title="Görev panosu" />{data.coachTasks.length ? <View style={{ gap: 9 }}>{data.coachTasks.map((task) => <TouchableOpacity key={task.id} onPress={() => toggleCoachTask(task.id)} style={[styles.task, task.completed && styles.taskDone]}><View style={[styles.check, task.completed && styles.checked]}><MaterialIcons name={task.completed ? "check" : "circle"} size={19} color={task.completed ? "#10150B" : "#657386"} /></View><View style={{ flex: 1 }}><Text style={[styles.taskTitle, task.completed && styles.taskTitleDone]}>{task.title}</Text>{task.description ? <Text style={styles.taskCopy}>{task.description}</Text> : null}</View></TouchableOpacity>)}</View> : <Card><Text style={styles.empty}>Henüz görev yok. Bir kontrol noktası ekleyerek çalışma alanını başlat.</Text></Card>}</ScrollView></View>;
}
const styles = StyleSheet.create({ back: { marginTop: 12, marginBottom: 24, flexDirection: "row", alignItems: "center", gap: 7 }, backText: { color: "#C5CDD7", fontSize: 13, fontWeight: "800" }, statusRow: { flexDirection: "row", gap: 11, alignItems: "center" }, statusIcon: { width: 40, height: 40, borderRadius: 13, backgroundColor: "#273116", alignItems: "center", justifyContent: "center" }, statusTitle: { color: "#F5F7FA", fontSize: 14, fontWeight: "900" }, statusCopy: { color: "#9AA6B5", fontSize: 11, lineHeight: 16, marginTop: 4 }, input: { minHeight: 48, paddingHorizontal: 13, borderWidth: 1, borderColor: "#344154", borderRadius: 13, backgroundColor: "#0B0E12", color: "#F5F7FA", fontSize: 14, fontWeight: "700" }, note: { minHeight: 78, marginTop: 9, paddingTop: 12, textAlignVertical: "top", fontWeight: "400" }, task: { padding: 13, gap: 11, flexDirection: "row", borderRadius: 17, backgroundColor: "#141A22", borderColor: "#263141", borderWidth: 1 }, taskDone: { backgroundColor: "#161F16", borderColor: "#526D24" }, check: { width: 32, height: 32, borderRadius: 10, backgroundColor: "#0B0E12", borderColor: "#344154", borderWidth: 1, alignItems: "center", justifyContent: "center" }, checked: { backgroundColor: "#B8FF3D", borderColor: "#B8FF3D" }, taskTitle: { color: "#F5F7FA", fontSize: 14, fontWeight: "900" }, taskTitleDone: { color: "#B8FF3D", textDecorationLine: "line-through" }, taskCopy: { color: "#9AA6B5", fontSize: 12, lineHeight: 18, marginTop: 4 }, empty: { color: "#9AA6B5", fontSize: 13, textAlign: "center", paddingVertical: 4 } });
