import { MaterialIcons } from "@expo/vector-icons";
import { CameraView, useCameraPermissions } from "expo-camera";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { Card, PrimaryButton, ui } from "@/components/fitness-ui";

const cues = ["Telefonu gövdenin tamamı kadraja girecek şekilde sabitle.", "Hareket düzlemine dik açıyla, yaklaşık kalça yüksekliğinden çekim yap.", "Aydınlık bir ortam seç; kontrastı yüksek, sade kıyafet kullan."];

export default function FormLabScreen() {
  const router = useRouter(); const [permission, requestPermission] = useCameraPermissions(); const [facing, setFacing] = useState<"front" | "back">("back"); const [consent, setConsent] = useState(false);
  return <View style={ui.page}><ScrollView contentContainerStyle={ui.content}><TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#D7DEE8" /><Text style={styles.backText}>Performans</Text></TouchableOpacity><Text style={ui.eyebrow}>Form Laboratuvarı</Text><Text style={ui.h1}>Tekniğini hizala.</Text><Text style={[ui.body, { marginTop: 8 }]}>Kamera önizlemesi yalnızca cihazında çalışır. Bu ilk sürüm, görüntüyü yüklemeden kadraj ve teknik kontrol rehberi sunar.</Text><View style={styles.privacy}><MaterialIcons name="lock-outline" size={18} color="#B8FF3D" /><Text style={styles.privacyText}>Kamera görüntüsü paylaşılmaz, sunucuya yüklenmez ve cihazında kalır.</Text></View>
    {!permission ? <Card><Text style={styles.wait}>Kamera izni kontrol ediliyor…</Text></Card> : !permission.granted ? <Card><Text style={styles.permissionTitle}>Kamera erişimi gerekli</Text><Text style={styles.permissionCopy}>Canlı kadraj rehberi için yalnızca kamera önizlemesine erişim ister.</Text><View style={{ marginTop: 15 }}><PrimaryButton label="Kamera İznini Ver" onPress={requestPermission} icon="videocam" /></View></Card> : <View style={styles.previewShell}><CameraView style={styles.camera} facing={facing}><View style={styles.frame}><View style={styles.frameCorner} /></View><View style={styles.previewTop}><View style={styles.livePill}><View style={styles.liveDot} /><Text style={styles.liveText}>YEREL ÖNİZLEME</Text></View><TouchableOpacity onPress={() => setFacing((current) => current === "back" ? "front" : "back")} style={styles.flip}><MaterialIcons name="flip-camera-android" size={20} color="#F5F7FA" /></TouchableOpacity></View><View style={styles.previewBottom}><Text style={styles.previewHint}>Tüm vücudun kadraj içinde kalsın</Text></View></CameraView></View>}
    <Text style={styles.sectionTitle}>Çekim öncesi kontrol</Text>{cues.map((cue, index) => <Card key={cue}><View style={styles.cueRow}><View style={styles.cueNumber}><Text style={styles.cueNumberText}>{index + 1}</Text></View><Text style={styles.cueText}>{cue}</Text></View></Card>)}
    <TouchableOpacity onPress={() => setConsent(!consent)} style={[styles.consent, consent && styles.consentActive]}><MaterialIcons name={consent ? "check-box" : "check-box-outline-blank"} size={21} color={consent ? "#B8FF3D" : "#9AA6B5"} /><Text style={styles.consentText}>Görüntünün yalnızca bu cihazda analiz rehberi için kullanılacağını anlıyorum.</Text></TouchableOpacity><Text style={styles.notice}>Bu ekran tıbbi tanı koymaz. Keskin ağrı, dengesizlik veya sakatlık şüphesinde uzman desteği al.</Text></ScrollView></View>;
}
const styles = StyleSheet.create({ back: { marginTop: 12, marginBottom: 24, flexDirection: "row", alignItems: "center", gap: 7 }, backText: { color: "#C5CDD7", fontSize: 13, fontWeight: "800" }, privacy: { marginTop: 17, padding: 12, borderRadius: 14, gap: 8, flexDirection: "row", alignItems: "center", backgroundColor: "#161F16", borderWidth: 1, borderColor: "#526D2444" }, privacyText: { color: "#C5CDD7", fontSize: 11, lineHeight: 16, flex: 1 }, wait: { color: "#9AA6B5", textAlign: "center", paddingVertical: 12 }, permissionTitle: { color: "#F5F7FA", fontSize: 15, fontWeight: "900" }, permissionCopy: { color: "#9AA6B5", fontSize: 12, lineHeight: 18, marginTop: 5 }, previewShell: { height: 390, borderRadius: 24, overflow: "hidden", marginTop: 19, backgroundColor: "#141A22" }, camera: { flex: 1, justifyContent: "space-between" }, previewTop: { padding: 14, flexDirection: "row", justifyContent: "space-between" }, livePill: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 8, paddingVertical: 6, borderRadius: 99, backgroundColor: "#0B0E12CC" }, liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#B8FF3D" }, liveText: { color: "#D7DEE8", fontSize: 9, fontWeight: "900", letterSpacing: 0.6 }, flip: { width: 38, height: 38, borderRadius: 13, backgroundColor: "#0B0E12CC", alignItems: "center", justifyContent: "center" }, frame: { position: "absolute", top: 64, left: "14%", right: "14%", bottom: 60, borderColor: "#B8FF3D99", borderWidth: 1, borderRadius: 98 }, frameCorner: { position: "absolute", top: -2, left: -2, width: 38, height: 38, borderLeftWidth: 4, borderTopWidth: 4, borderColor: "#B8FF3D", borderTopLeftRadius: 20 }, previewBottom: { padding: 14, alignItems: "center" }, previewHint: { color: "#F5F7FA", fontSize: 11, fontWeight: "800", paddingHorizontal: 11, paddingVertical: 7, borderRadius: 99, backgroundColor: "#0B0E12CC" }, sectionTitle: { color: "#F5F7FA", fontSize: 18, fontWeight: "900", marginTop: 25, marginBottom: 11 }, cueRow: { flexDirection: "row", gap: 10, alignItems: "center" }, cueNumber: { width: 28, height: 28, borderRadius: 10, backgroundColor: "#1B2A17", alignItems: "center", justifyContent: "center" }, cueNumberText: { color: "#B8FF3D", fontWeight: "900" }, cueText: { color: "#D7DEE8", fontSize: 12, lineHeight: 18, flex: 1 }, consent: { marginTop: 16, padding: 12, borderRadius: 14, backgroundColor: "#141A22", borderWidth: 1, borderColor: "#344154", flexDirection: "row", gap: 9, alignItems: "flex-start" }, consentActive: { borderColor: "#526D24" }, consentText: { color: "#C5CDD7", fontSize: 11, lineHeight: 16, flex: 1 }, notice: { color: "#728094", fontSize: 11, lineHeight: 16, textAlign: "center", marginTop: 15 } });
