import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { Card, EmptyState, PrimaryButton, SectionTitle, ui } from "@/components/fitness-ui";
import { useFitness } from "@/lib/fitness-store";
import { exerciseById } from "@/shared/fitness";

const asDate = (value: string) => new Date(`${value}T12:00:00`);
const dateLabel = (value: string) => new Intl.DateTimeFormat("tr-TR", { weekday: "short", day: "numeric", month: "short" }).format(asDate(value));

export default function PlannerScreen() {
  const router = useRouter(); const { data, scheduleTemplate, rescheduleWorkout } = useFitness();
  const [templateId, setTemplateId] = useState(data.templates[0]?.id ?? ""); const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const entries = useMemo(() => [...data.schedule].sort((a, b) => a.scheduledFor.localeCompare(b.scheduledFor)), [data.schedule]);
  const templateName = (id: string) => data.templates.find((item) => item.id === id)?.name ?? "Program";
  const missed = entries.filter((item) => item.scheduledFor < new Date().toISOString().slice(0, 10) && item.status === "planned");
  return <View style={ui.page}><ScrollView contentContainerStyle={ui.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#D7DEE8" /><Text style={styles.backText}>Performans</Text></TouchableOpacity><Text style={ui.eyebrow}>Akıllı Planlayıcı</Text><Text style={ui.h1}>Ritmini koru.</Text><Text style={[ui.body, { marginTop: 8 }]}>Planlanan antrenmanlar kaçırıldığında, haftanı bozmadan yeni güne taşı.</Text>
    {missed.length ? <Card accent><View style={styles.missedRow}><MaterialIcons name="event-busy" color="#F9B371" size={20} /><View style={{ flex: 1 }}><Text style={styles.missedTitle}>{missed.length} antrenman yeniden planlanabilir</Text><Text style={styles.missedCopy}>Tarihe dokunarak planı yarına taşıyabilirsin.</Text></View></View></Card> : null}
    <SectionTitle title="Programa ekle" />{data.templates.length ? <Card><Text style={styles.label}>Antrenman şablonu</Text><View style={styles.templateRow}>{data.templates.map((template) => <TouchableOpacity key={template.id} onPress={() => setTemplateId(template.id)} style={[styles.template, templateId === template.id && styles.templateActive]}><Text style={[styles.templateText, templateId === template.id && styles.templateTextActive]}>{template.name}</Text></TouchableOpacity>)}</View><Text style={[styles.label, { marginTop: 14 }]}>Tarih</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-AA-GG" placeholderTextColor="#657386" style={styles.input} /><View style={{ marginTop: 15 }}><PrimaryButton label="Takvime Ekle" onPress={() => templateId && scheduleTemplate(templateId, date)} icon="event" /></View></Card> : <EmptyState icon="calendar-month" title="Önce bir program oluştur" copy="Takvime eklemek için Antrenman sekmesinden bir şablon oluştur." onAction={() => router.push("/train" as never)} action="Antrenmana Git" />}
    <SectionTitle title="Yaklaşan plan" />{entries.length ? <View style={{ gap: 9 }}>{entries.map((entry) => { const template = data.templates.find((item) => item.id === entry.templateId); const muscle = template?.exercises[0] ? exerciseById(template.exercises[0].exerciseId)?.primaryMuscles[0] : undefined; return <Card key={entry.id}><View style={styles.scheduleRow}><View style={styles.dateBox}><Text style={styles.dateDay}>{dateLabel(entry.scheduledFor)}</Text><Text style={styles.dateStatus}>{entry.scheduledFor < new Date().toISOString().slice(0, 10) ? "KAÇTI" : "PLANLI"}</Text></View><View style={{ flex: 1 }}><Text style={styles.scheduleName}>{templateName(entry.templateId)}</Text><Text style={styles.scheduleCopy}>{muscle ? `${muscle} odaklı` : "Program hazır"}</Text></View>{entry.scheduledFor < new Date().toISOString().slice(0, 10) ? <TouchableOpacity onPress={() => rescheduleWorkout(entry.id, new Date(Date.now() + 86_400_000).toISOString().slice(0, 10))} style={styles.move}><MaterialIcons name="update" size={18} color="#B8FF3D" /></TouchableOpacity> : null}</View></Card>; })}</View> : <EmptyState icon="event" title="Takvim boş" copy="Haftanı düzenlemek için programlarından birini takvime ekle." />}</ScrollView></View>;
}
const styles = StyleSheet.create({ back: { marginTop: 12, marginBottom: 24, flexDirection: "row", alignItems: "center", gap: 7 }, backText: { color: "#C5CDD7", fontSize: 13, fontWeight: "800" }, missedRow: { flexDirection: "row", gap: 10, alignItems: "center" }, missedTitle: { color: "#F5F7FA", fontWeight: "900", fontSize: 14 }, missedCopy: { color: "#9AA6B5", fontSize: 11, marginTop: 4 }, label: { color: "#9AA6B5", fontSize: 11, fontWeight: "800" }, templateRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 8 }, template: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10, borderWidth: 1, borderColor: "#344154", backgroundColor: "#0B0E12" }, templateActive: { backgroundColor: "#B8FF3D", borderColor: "#B8FF3D" }, templateText: { color: "#C5CDD7", fontSize: 11, fontWeight: "800" }, templateTextActive: { color: "#10150B" }, input: { marginTop: 6, minHeight: 46, paddingHorizontal: 12, borderColor: "#344154", borderWidth: 1, borderRadius: 12, backgroundColor: "#0B0E12", color: "#F5F7FA", fontWeight: "800" }, scheduleRow: { flexDirection: "row", gap: 11, alignItems: "center" }, dateBox: { minWidth: 68, padding: 9, borderRadius: 12, backgroundColor: "#1B2430", alignItems: "center" }, dateDay: { color: "#D7DEE8", fontSize: 10, fontWeight: "900" }, dateStatus: { color: "#F9B371", fontSize: 8, fontWeight: "900", marginTop: 3 }, scheduleName: { color: "#F5F7FA", fontSize: 14, fontWeight: "900" }, scheduleCopy: { color: "#9AA6B5", fontSize: 11, marginTop: 3 }, move: { width: 35, height: 35, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#1B2A17" } });
