import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";

import { Card, PrimaryButton, SectionTitle, ui } from "@/components/fitness-ui";
import { useFitness } from "@/lib/fitness-store";

const EQUIPMENT = ["Barbell", "Dumbbell", "Cable", "Machine", "Bodyweight"];

export default function TrainingSetupScreen() {
  const router = useRouter(); const { data, updateEquipmentProfile, updatePartner } = useFitness(); const [name, setName] = useState(data.partner.displayName ?? ""); const [code, setCode] = useState(data.partner.inviteCode ?? "");
  const toggleEquipment = (item: string) => updateEquipmentProfile(data.equipmentProfile.includes(item) ? data.equipmentProfile.filter((current) => current !== item) : [...data.equipmentProfile, item]);
  return <View style={ui.page}><ScrollView contentContainerStyle={ui.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#D7DEE8" /><Text style={styles.backText}>Performans</Text></TouchableOpacity><Text style={ui.eyebrow}>Antrenman Kurulumu</Text><Text style={ui.h1}>Çevrene uyum sağla.</Text><Text style={[ui.body, { marginTop: 8 }]}>Kendi salonundaki ekipmanı seç; partner antrenmanı için paylaşılan kodunu hazırla.</Text><SectionTitle title="Salon ekipmanın" /><Card><Text style={styles.copy}>Kütüphane ve öneriler, seçtiğin ekipmanla yapılabilecek hareketleri önceliklendirebilir.</Text><View style={styles.equipment}>{EQUIPMENT.map((item) => <TouchableOpacity key={item} onPress={() => toggleEquipment(item)} style={[styles.equipmentChip, data.equipmentProfile.includes(item) && styles.equipmentActive]}><MaterialIcons name={data.equipmentProfile.includes(item) ? "check-circle" : "add-circle-outline"} size={16} color={data.equipmentProfile.includes(item) ? "#10150B" : "#9AA6B5"} /><Text style={[styles.equipmentText, data.equipmentProfile.includes(item) && styles.equipmentTextActive]}>{item}</Text></TouchableOpacity>)}</View></Card><SectionTitle title="Partnerli antrenman" /><Card accent><View style={styles.partnerTop}><View style={styles.partnerIcon}><MaterialIcons name="group" size={22} color="#B8FF3D" /></View><View style={{ flex: 1 }}><Text style={styles.partnerTitle}>Partner modunu etkinleştir</Text><Text style={styles.partnerCopy}>Aktif antrenmanda sırayla set alma ve ortak dinlenme notlarını gör.</Text></View><Switch value={data.partner.enabled} onValueChange={(enabled) => updatePartner({ enabled })} trackColor={{ false: "#344154", true: "#668B26" }} thumbColor={data.partner.enabled ? "#B8FF3D" : "#C5CDD7"} /></View>{data.partner.enabled ? <View style={styles.form}><TextInput value={name} onChangeText={setName} placeholder="Partner adı" placeholderTextColor="#657386" style={styles.input} /><TextInput value={code} onChangeText={setCode} placeholder="Paylaşım kodu (isteğe bağlı)" placeholderTextColor="#657386" style={styles.input} /><PrimaryButton label="Partneri Kaydet" onPress={() => updatePartner({ enabled: true, displayName: name.trim() || undefined, inviteCode: code.trim() || undefined })} icon="link" /></View> : null}</Card></ScrollView></View>;
}
const styles = StyleSheet.create({ back: { marginTop: 12, marginBottom: 24, flexDirection: "row", alignItems: "center", gap: 7 }, backText: { color: "#C5CDD7", fontSize: 13, fontWeight: "800" }, copy: { color: "#9AA6B5", fontSize: 12, lineHeight: 18 }, equipment: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 }, equipmentChip: { flexDirection: "row", gap: 5, alignItems: "center", paddingHorizontal: 10, paddingVertical: 9, borderRadius: 11, backgroundColor: "#0B0E12", borderColor: "#344154", borderWidth: 1 }, equipmentActive: { backgroundColor: "#B8FF3D", borderColor: "#B8FF3D" }, equipmentText: { color: "#C5CDD7", fontSize: 11, fontWeight: "800" }, equipmentTextActive: { color: "#10150B" }, partnerTop: { flexDirection: "row", alignItems: "center", gap: 10 }, partnerIcon: { width: 41, height: 41, borderRadius: 13, backgroundColor: "#273116", alignItems: "center", justifyContent: "center" }, partnerTitle: { color: "#F5F7FA", fontSize: 14, fontWeight: "900" }, partnerCopy: { color: "#9AA6B5", fontSize: 11, lineHeight: 16, marginTop: 3 }, form: { gap: 9, marginTop: 16 }, input: { minHeight: 46, paddingHorizontal: 12, borderRadius: 12, backgroundColor: "#0B0E12", borderColor: "#344154", borderWidth: 1, color: "#F5F7FA", fontSize: 13, fontWeight: "700" } });
