import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEvent } from "expo";
import { VideoView, useVideoPlayer } from "expo-video";
import { useState } from "react";
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import WebView from "react-native-webview";

const TRUSTED_HOSTS = new Set(["wger.de", "www.wger.de", "muscleandstrength.com", "www.muscleandstrength.com", "acefitness.org", "www.acefitness.org", "www.youtube.com", "youtube.com", "www.youtube-nocookie.com", "youtube-nocookie.com", "player.vimeo.com", "vimeo.com"]);

function isTrustedUrl(url: string) {
  try { return new URL(url).protocol === "https:" && TRUSTED_HOSTS.has(new URL(url).hostname); } catch { return false; }
}

export function InAppVideoGuide({ url, title, onBack, directVideo = false }: { url: string; title: string; onBack: () => void; directVideo?: boolean }) {
  const [loading, setLoading] = useState(true);
  const [failed, setFailed] = useState(false);
  if (!isTrustedUrl(url)) return <View style={styles.page}><Text style={styles.errorTitle}>Kaynak açılamadı</Text><Text style={styles.errorCopy}>Bu rehber yalnızca doğrulanmış HTTPS kaynakları için uygulama içinde açılır.</Text><TouchableOpacity onPress={onBack} style={styles.backButton}><Text style={styles.backText}>Geri dön</Text></TouchableOpacity></View>;
  return <View style={styles.page}><View style={styles.header}><TouchableOpacity accessibilityRole="button" onPress={onBack} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#E7EDF5" /></TouchableOpacity><View style={{ flex: 1 }}><Text style={styles.eyebrow}>UYGULAMA İÇİ VİDEO REHBERİ</Text><Text numberOfLines={1} style={styles.title}>{title}</Text></View></View><View style={styles.source}><MaterialIcons name="verified-user" size={15} color="#B8FF3D" /><Text style={styles.sourceText}>Doğrulanmış kaynak uygulama içinden görüntüleniyor.</Text></View>{directVideo ? <DirectVideoPlayer source={url} /> : <View style={styles.webviewShell}>{failed ? <View style={styles.fallback}><MaterialIcons name="error-outline" size={27} color="#FFD166" /><Text style={styles.errorTitle}>Kaynak sayfa yüklenemedi</Text><Text style={styles.errorCopy}>Bağlantını kontrol et. Bu ekran uygulamadan çıkmadan kapatılabilir; doğrulanmış form rehberi egzersiz sayfasında kullanılabilir.</Text><TouchableOpacity onPress={onBack} style={styles.backButton}><Text style={styles.backText}>Teknik rehbere dön</Text></TouchableOpacity></View> : <WebView source={{ uri: url }} originWhitelist={["https://*"]} onLoadStart={() => setLoading(true)} onLoadEnd={() => setLoading(false)} onError={() => { setLoading(false); setFailed(true); }} onHttpError={() => { setLoading(false); setFailed(true); }} onShouldStartLoadWithRequest={(request) => isTrustedUrl(request.url)} setSupportMultipleWindows={false} javaScriptCanOpenWindowsAutomatically={false} allowsBackForwardNavigationGestures style={styles.webview} />}{loading && !failed ? <View pointerEvents="none" style={styles.loading}><ActivityIndicator color="#B8FF3D" size="large" /><Text style={styles.loadingTitle}>Video rehberi hazırlanıyor</Text><Text style={styles.loadingCopy}>Uygulama içindeki güvenli görüntüleyici açılıyor.</Text></View> : null}</View>}</View>;
}

function DirectVideoPlayer({ source }: { source: string }) {
  const player = useVideoPlayer(source, (instance) => { instance.loop = false; });
  const { status, error } = useEvent(player, "statusChange", { status: player.status });
  return <View style={styles.videoShell}><VideoView style={styles.video} player={player} fullscreenOptions={{ enable: true }} allowsPictureInPicture nativeControls contentFit="contain" surfaceType="textureView" />{status === "loading" ? <View pointerEvents="none" style={styles.loading}><ActivityIndicator color="#B8FF3D" size="large" /><Text style={styles.loadingTitle}>Video hazırlanıyor</Text><Text style={styles.loadingCopy}>Doğrulanmış video uygulama içinde oynatılacak.</Text></View> : null}{error ? <View style={styles.fallback}><MaterialIcons name="error-outline" size={27} color="#FFD166" /><Text style={styles.errorTitle}>Video oynatılamadı</Text><Text style={styles.errorCopy}>Bağlantını kontrol et; ayrıntılı form rehberi egzersiz sayfasında kullanılabilir.</Text></View> : null}</View>;
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#090D12", paddingTop: 54 }, header: { paddingHorizontal: 20, paddingBottom: 14, flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#141A22", borderColor: "#344154", borderWidth: 1, alignItems: "center", justifyContent: "center" }, eyebrow: { color: "#B8FF3D", fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, title: { color: "#F5F7FA", fontSize: 16, fontWeight: "900", marginTop: 3 }, source: { marginHorizontal: 20, marginBottom: 12, padding: 10, borderRadius: 12, backgroundColor: "#16251A", flexDirection: "row", alignItems: "center", gap: 7 }, sourceText: { color: "#CFE6B3", fontSize: 10, fontWeight: "700" }, webviewShell: { flex: 1, marginHorizontal: 12, marginBottom: 12, overflow: "hidden", borderRadius: 20, borderColor: "#2B3748", borderWidth: 1, backgroundColor: "#05080C" }, videoShell: { flex: 1, marginHorizontal: 12, marginBottom: 12, overflow: "hidden", borderRadius: 20, borderColor: "#2B3748", borderWidth: 1, backgroundColor: "#05080C" }, video: { flex: 1 }, webview: { flex: 1, backgroundColor: "#05080C" }, loading: { position: "absolute" as const, top: 0, left: 0, right: 0, bottom: 0, alignItems: "center", justifyContent: "center", backgroundColor: "#090D12" }, loadingTitle: { color: "#F5F7FA", fontSize: 15, fontWeight: "900", marginTop: 14 }, loadingCopy: { color: "#9AA6B5", fontSize: 11, marginTop: 5 }, fallback: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28 }, errorTitle: { color: "#F5F7FA", fontSize: 17, fontWeight: "900", textAlign: "center", marginTop: 12 }, errorCopy: { color: "#B7C0CB", fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 7 }, backButton: { marginTop: 20, paddingHorizontal: 16, paddingVertical: 11, borderRadius: 13, backgroundColor: "#B8FF3D" }, backText: { color: "#10150B", fontSize: 12, fontWeight: "900" },
});
